apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api
        image: movie-recommender:latest
        ports:
        - containerPort: 8000
